server:
  port: 8086
  servlet:
    context-path: /customerservices
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/bankmanagement
   # username: root
   # password: pass@word1
  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka
